site_name: Environmental Biophysics
repo_url: https://github.com/gcamargo1/environmental-biophysics
repo_name: gcamargo1/environmental-biophysics
edit_uri: tree/main/docs

theme:
  name: material

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.tasklist

extra_css:
  - stylesheets/extra.css

watch:
   - environmental_biophysics

plugins:
- macros
- mkdocstrings:
    handlers:
      python:
        paths: [environmental_biophysics]

extra:
  commands:
    run: environmental-biophysics
