# .github/workflows/push_workflow.yml
name: push
on:
  push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: eifinger/setup-rye@v3
      - run: rye pin 3.12         # pin your Python version
      - run: rye sync
      - run: rye fmt --check      # check formatting is correct
      - run: rye lint             # and linting
      - run: rye run test         # then run your tests!
      - uses: jakebailey/pyright-action@v2
      - run: rye run check        # typecheck too
